# Generated by Django 5.0.7 on 2024-07-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starcraftrank', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('master', 'Master'), ('grandmaster', 'Grandmaster'), ('n/a', 'N/A')], default='n/a', max_length=100)),
                ('starcraftrace', models.CharField(choices=[('terran', 'Terran'), ('zerg', 'Zerg'), ('protoss', 'Protoss'), ('n/a', 'N/A')], default='n/a', max_length=100)),
                ('leaguerank', models.CharField(choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('emerald', 'Emerald'), ('diamond', 'Diamond'), ('master', 'Master'), ('grandmaster', 'Grandmaster'), ('challenger', 'Challenger'), ('n/a', 'N/A')], default='n/a', max_length=100)),
                ('leaguerole', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support'), ('fill', 'Fill'), ('n/a', 'N/A')], default='n/a', max_length=100)),
                ('leaguesecondaryrole', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support'), ('fill', 'Fill'), ('n/a', 'N/A')], default='n/a', max_length=100)),
                ('cs2elo', models.IntegerField(choices=[(0, '0'), (1000, '1000'), (2000, '2000'), (3000, '3000'), (4000, '4000'), (5000, '5000'), (6000, '6000'), (7000, '7000'), (8000, '8000'), (9000, '9000'), (10000, '10000'), (11000, '11000'), (12000, '12000'), (13000, '13000'), (14000, '14000'), (15000, '15000'), (16000, '16000'), (17000, '17000'), (18000, '18000'), (19000, '19000'), (20000, '20000'), (21000, '21000'), (22000, '22000'), (23000, '23000'), (24000, '24000'), (25000, '25000'), (26000, '26000'), (27000, '27000'), (28000, '28000'), (29000, '29000'), (30000, '30000')], default=0)),
                ('profimage', models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/')),
            ],
        ),
    ]
