# Generated by Django 5.0.7 on 2024-07-12 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('Starcraft', 'Starcraft'), ('League of Legends', 'League of Legends'), ('Counterstrike 2', 'Counterstrike 2'), ('Multigame', 'Multigame'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
