# Generated by Django 5.0.7 on 2024-07-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_created_by_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.CharField(choices=[('Starcraft', 'Starcraft'), ('League of Legends', 'League of Legends'), ('Counterstrike 2', 'Counterstrike 2'), ('Multigame', 'Multigame'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
