# Generated by Django 5.0.7 on 2024-07-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_game_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('id', 'name')},
        ),
    ]
